export type Century = 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;

export type Faction = {
  id: string;
  name: string;
  color: number;
};

export type CenturyScenario = {
  century: Century;
  title: string;
  subtitle: string;
  note: string;
  factions: Faction[];
  ownership: Record<string, string>;
};

export const scenarios: Record<Century, CenturyScenario> = {
  5: {
    century: 5,
    title: 'The fall of the Western Empire',
    subtitle: 'Germanic kingdoms carve up the Roman west.',
    note: '476 AD. Odoacer deposes Romulus Augustulus. The western provinces are now ruled by successor kingdoms while the Eastern Empire endures.',
    factions: [
      { id: 'franks', name: 'Franks', color: 0x8f473e },
      { id: 'visigoths', name: 'Visigoths', color: 0xb8794d },
      { id: 'ostrogoths', name: 'Ostrogoths', color: 0xb6a26a },
      { id: 'byzantines', name: 'Eastern Romans', color: 0x344e5c },
      { id: 'saxons', name: 'Anglo-Saxons', color: 0x607a68 },
      { id: 'vandals', name: 'Vandals', color: 0x9b6b58 },
    ],
    ownership: {
      britannia: 'saxons', caledonia: 'saxons', hibernia: 'saxons',
      gallia: 'franks', aquitania: 'visigoths', hispania: 'visigoths',
      italia: 'ostrogoths', sicilia: 'ostrogoths',
      germania: 'franks', raetia: 'ostrogoths',
      pannonia: 'ostrogoths', illyricum: 'ostrogoths',
      moesia: 'byzantines', thracia: 'byzantines',
      graecia: 'byzantines', dacia: 'byzantines',
      sarmatia: 'franks', scandinavia: 'saxons',
      africa: 'vandals', scythia: 'byzantines',
    },
  },
  6: {
    century: 6,
    title: 'The age of Justinian',
    subtitle: 'Imperial reconquest and the rise of the Franks.',
    note: '527-565 AD. Justinian reclaims Africa, Italy, and parts of Hispania. The Frankish kingdoms consolidate while the Lombards prepare to enter Italy.',
    factions: [
      { id: 'franks', name: 'Frankish kingdoms', color: 0x8f473e },
      { id: 'byzantines', name: 'Eastern Romans', color: 0x344e5c },
      { id: 'visigoths', name: 'Visigoths', color: 0xb8794d },
      { id: 'saxons', name: 'Anglo-Saxons', color: 0x607a68 },
      { id: 'lombards', name: 'Lombards', color: 0xb6a26a },
      { id: 'avars', name: 'Avars & Slavs', color: 0x7d8c60 },
    ],
    ownership: {
      britannia: 'saxons', caledonia: 'saxons', hibernia: 'saxons',
      gallia: 'franks', aquitania: 'franks', hispania: 'visigoths',
      italia: 'byzantines', sicilia: 'byzantines',
      germania: 'franks', raetia: 'lombards',
      pannonia: 'avars', illyricum: 'byzantines',
      moesia: 'byzantines', thracia: 'byzantines',
      graecia: 'byzantines', dacia: 'avars',
      sarmatia: 'avars', scandinavia: 'saxons',
      africa: 'byzantines', scythia: 'byzantines',
    },
  },
  7: {
    century: 7,
    title: 'Kingdoms and frontiers',
    subtitle: 'Merovingian power, the rise of Islam, and new movements in the east.',
    note: 'The Merovingian Franks dominate the west. The Visigothic kingdom spans Hispania. Islam emerges to transform the southern Mediterranean. Bulgars cross the Danube.',
    factions: [
      { id: 'franks', name: 'Frankish kingdoms', color: 0x8f473e },
      { id: 'byzantines', name: 'Eastern Romans', color: 0x344e5c },
      { id: 'visigoths', name: 'Visigoths', color: 0xb8794d },
      { id: 'saxons', name: 'Anglo-Saxons', color: 0x607a68 },
      { id: 'lombards', name: 'Lombard kingdom', color: 0xb6a26a },
      { id: 'bulgars', name: 'Bulgar khanate', color: 0x9b6b58 },
    ],
    ownership: {
      britannia: 'saxons', caledonia: 'saxons', hibernia: 'saxons',
      gallia: 'franks', aquitania: 'franks', hispania: 'visigoths',
      italia: 'lombards', sicilia: 'byzantines',
      germania: 'franks', raetia: 'lombards',
      pannonia: 'bulgars', illyricum: 'byzantines',
      moesia: 'bulgars', thracia: 'byzantines',
      graecia: 'byzantines', dacia: 'bulgars',
      sarmatia: 'bulgars', scandinavia: 'saxons',
      africa: 'byzantines', scythia: 'byzantines',
    },
  },
  8: {
    century: 8,
    title: 'The Carolingian ascent',
    subtitle: 'Charlemagne builds a new western empire.',
    note: 'Charles Martel halts the Umayyad advance at Tours. Charlemagne is crowned Emperor in 800. The Byzantine Empire fights for survival against the Caliphate and Bulgars.',
    factions: [
      { id: 'carolingians', name: 'Carolingians', color: 0x8f473e },
      { id: 'byzantines', name: 'Eastern Romans', color: 0x344e5c },
      { id: 'umayyads', name: 'Umayyad Spain', color: 0x7d8c60 },
      { id: 'saxons', name: 'Anglo-Saxons', color: 0x607a68 },
      { id: 'lombards', name: 'Lombard kingdom', color: 0xb6a26a },
      { id: 'bulgars', name: 'Bulgar khanate', color: 0xb8794d },
    ],
    ownership: {
      britannia: 'saxons', caledonia: 'saxons', hibernia: 'saxons',
      gallia: 'carolingians', aquitania: 'carolingians', hispania: 'umayyads',
      italia: 'lombards', sicilia: 'byzantines',
      germania: 'carolingians', raetia: 'carolingians',
      pannonia: 'bulgars', illyricum: 'byzantines',
      moesia: 'bulgars', thracia: 'byzantines',
      graecia: 'byzantines', dacia: 'bulgars',
      sarmatia: 'bulgars', scandinavia: 'saxons',
      africa: 'umayyads', scythia: 'byzantines',
    },
  },
  9: {
    century: 9,
    title: 'The empire divides',
    subtitle: 'Carolingian inheritance fragments into rival realms.',
    note: 'The Treaty of Verdun (843) splits the Frankish empire into three. Viking raids reshape the north. The Macedonian dynasty revives Byzantine power.',
    factions: [
      { id: 'west-francia', name: 'West Francia', color: 0x8f473e },
      { id: 'east-francia', name: 'East Francia', color: 0x607a68 },
      { id: 'byzantines', name: 'Eastern Romans', color: 0x344e5c },
      { id: 'umayyads', name: 'Umayyad Spain', color: 0x7d8c60 },
      { id: 'bulgars', name: 'Bulgar empire', color: 0xb8794d },
      { id: 'vikings', name: 'Norse realms', color: 0xb6a26a },
    ],
    ownership: {
      britannia: 'west-francia', caledonia: 'vikings', hibernia: 'vikings',
      gallia: 'west-francia', aquitania: 'west-francia', hispania: 'umayyads',
      italia: 'east-francia', sicilia: 'byzantines',
      germania: 'east-francia', raetia: 'east-francia',
      pannonia: 'bulgars', illyricum: 'byzantines',
      moesia: 'bulgars', thracia: 'byzantines',
      graecia: 'byzantines', dacia: 'bulgars',
      sarmatia: 'east-francia', scandinavia: 'vikings',
      africa: 'umayyads', scythia: 'byzantines',
    },
  },
  10: {
    century: 10,
    title: 'The new imperial age',
    subtitle: 'Ottonian Germany, the Macedonian renaissance, and frontier kingdoms.',
    note: 'Otto I crowned Emperor (962). The Capetians rise in West Francia. The Bulgarian empire reaches its zenith before Byzantine reconquest under Basil II.',
    factions: [
      { id: 'ottonians', name: 'Ottonian realm', color: 0x607a68 },
      { id: 'capetians', name: 'West Francia', color: 0x8f473e },
      { id: 'byzantines', name: 'Eastern Romans', color: 0x344e5c },
      { id: 'caliphate', name: 'Caliphate of Cordoba', color: 0x7d8c60 },
      { id: 'bulgars', name: 'Bulgar empire', color: 0xb8794d },
      { id: 'vikings', name: 'Norse realms', color: 0xb6a26a },
    ],
    ownership: {
      britannia: 'vikings', caledonia: 'vikings', hibernia: 'vikings',
      gallia: 'capetians', aquitania: 'capetians', hispania: 'caliphate',
      italia: 'ottonians', sicilia: 'byzantines',
      germania: 'ottonians', raetia: 'ottonians',
      pannonia: 'ottonians', illyricum: 'bulgars',
      moesia: 'bulgars', thracia: 'byzantines',
      graecia: 'byzantines', dacia: 'bulgars',
      sarmatia: 'ottonians', scandinavia: 'vikings',
      africa: 'caliphate', scythia: 'byzantines',
    },
  },
  11: {
    century: 11,
    title: 'The high medieval threshold',
    subtitle: 'Norman conquests, the Investiture Crisis, and Crusader ambition.',
    note: '1066 AD. William the Conqueror takes England. The Seljuk Turks defeat Byzantium at Manzikert (1071). The First Crusade captures Jerusalem (1099).',
    factions: [
      { id: 'hre', name: 'Holy Roman Empire', color: 0x607a68 },
      { id: 'france', name: 'Kingdom of France', color: 0x8f473e },
      { id: 'byzantines', name: 'Eastern Romans', color: 0x344e5c },
      { id: 'england', name: 'Norman England', color: 0xb8794d },
      { id: 'papacy', name: 'Papal States', color: 0xb6a26a },
      { id: 'kiev', name: 'Kievan Rus', color: 0x9b6b58 },
    ],
    ownership: {
      britannia: 'england', caledonia: 'england', hibernia: 'england',
      gallia: 'france', aquitania: 'france', hispania: 'hre',
      italia: 'hre', sicilia: 'france',
      germania: 'hre', raetia: 'hre',
      pannonia: 'hre', illyricum: 'byzantines',
      moesia: 'byzantines', thracia: 'byzantines',
      graecia: 'byzantines', dacia: 'kiev',
      sarmatia: 'kiev', scandinavia: 'hre',
      africa: 'byzantines', scythia: 'kiev',
    },
  },
  12: {
    century: 12,
    title: 'The age of Crusades',
    subtitle: 'Plantagenets, Hohenstaufens, and the Crusader states.',
    note: 'Henry II builds the Angevin Empire. Frederick Barbarossa leads the Third Crusade. The Komnenian restoration revives Byzantium. Saladin retakes Jerusalem.',
    factions: [
      { id: 'hre', name: 'Holy Roman Empire', color: 0x607a68 },
      { id: 'france', name: 'Kingdom of France', color: 0x8f473e },
      { id: 'byzantines', name: 'Eastern Romans', color: 0x344e5c },
      { id: 'england', name: 'Angevin Empire', color: 0xb8794d },
      { id: 'papacy', name: 'Papal States', color: 0xb6a26a },
      { id: 'castile', name: 'Kingdom of Castile', color: 0x9b6b58 },
    ],
    ownership: {
      britannia: 'england', caledonia: 'england', hibernia: 'england',
      gallia: 'england', aquitania: 'england', hispania: 'castile',
      italia: 'hre', sicilia: 'hre',
      germania: 'hre', raetia: 'hre',
      pannonia: 'hre', illyricum: 'byzantines',
      moesia: 'byzantines', thracia: 'byzantines',
      graecia: 'byzantines', dacia: 'byzantines',
      sarmatia: 'hre', scandinavia: 'hre',
      africa: 'byzantines', scythia: 'byzantines',
    },
  },
  13: {
    century: 13,
    title: 'Empires and invasions',
    subtitle: 'Mongol storm, Magna Carta, and the rise of nation-states.',
    note: 'Genghis Khan unites the Mongol tribes (1206). Magna Carta signed (1215). The Teutonic Order conquers Prussia. The Reconquista advances in Iberia.',
    factions: [
      { id: 'hre', name: 'Holy Roman Empire', color: 0x607a68 },
      { id: 'france', name: 'Kingdom of France', color: 0x8f473e },
      { id: 'mongols', name: 'Mongol Empire', color: 0x344e5c },
      { id: 'england', name: 'Kingdom of England', color: 0xb8794d },
      { id: 'aragon', name: 'Crown of Aragon', color: 0xb6a26a },
      { id: 'castile', name: 'Kingdom of Castile', color: 0x9b6b58 },
    ],
    ownership: {
      britannia: 'england', caledonia: 'england', hibernia: 'england',
      gallia: 'france', aquitania: 'england', hispania: 'castile',
      italia: 'hre', sicilia: 'aragon',
      germania: 'hre', raetia: 'hre',
      pannonia: 'hre', illyricum: 'mongols',
      moesia: 'mongols', thracia: 'mongols',
      graecia: 'mongols', dacia: 'mongols',
      sarmatia: 'mongols', scandinavia: 'hre',
      africa: 'aragon', scythia: 'mongols',
    },
  },
  14: {
    century: 14,
    title: 'Crisis and calamity',
    subtitle: 'The Black Death, Hundred Years\' War, and Ottoman expansion.',
    note: 'The Black Death kills a third of Europe (1347-1351). England and France begin the Hundred Years\' War. The Ottomans cross into Europe. The papacy moves to Avignon.',
    factions: [
      { id: 'hre', name: 'Holy Roman Empire', color: 0x607a68 },
      { id: 'france', name: 'Kingdom of France', color: 0x8f473e },
      { id: 'ottomans', name: 'Ottoman Empire', color: 0x344e5c },
      { id: 'england', name: 'Kingdom of England', color: 0xb8794d },
      { id: 'papacy', name: 'Papal States', color: 0xb6a26a },
      { id: 'castile', name: 'Kingdom of Castile', color: 0x9b6b58 },
    ],
    ownership: {
      britannia: 'england', caledonia: 'england', hibernia: 'england',
      gallia: 'france', aquitania: 'england', hispania: 'castile',
      italia: 'papacy', sicilia: 'aragon',
      germania: 'hre', raetia: 'hre',
      pannonia: 'hre', illyricum: 'ottomans',
      moesia: 'ottomans', thracia: 'ottomans',
      graecia: 'ottomans', dacia: 'ottomans',
      sarmatia: 'hre', scandinavia: 'hre',
      africa: 'ottomans', scythia: 'ottomans',
    },
  },
  15: {
    century: 15,
    title: 'The dawn of a new era',
    subtitle: 'Fall of Constantinople, the Reconquista, and the Renaissance.',
    note: 'Constantinople falls to Mehmed II (1453). Spain is unified and Columbus reaches the Americas (1492). The Wars of the Roses divide England. The Renaissance transforms Europe.',
    factions: [
      { id: 'hre', name: 'Holy Roman Empire', color: 0x607a68 },
      { id: 'france', name: 'Kingdom of France', color: 0x8f473e },
      { id: 'ottomans', name: 'Ottoman Empire', color: 0x344e5c },
      { id: 'england', name: 'Kingdom of England', color: 0xb8794d },
      { id: 'spain', name: 'Crown of Spain', color: 0xb6a26a },
      { id: 'moscow', name: 'Grand Duchy of Moscow', color: 0x9b6b58 },
    ],
    ownership: {
      britannia: 'england', caledonia: 'england', hibernia: 'england',
      gallia: 'france', aquitania: 'france', hispania: 'spain',
      italia: 'hre', sicilia: 'spain',
      germania: 'hre', raetia: 'hre',
      pannonia: 'hre', illyricum: 'ottomans',
      moesia: 'ottomans', thracia: 'ottomans',
      graecia: 'ottomans', dacia: 'ottomans',
      sarmatia: 'moscow', scandinavia: 'hre',
      africa: 'ottomans', scythia: 'moscow',
    },
  },
};

export function getScenario(century: Century) {
  return scenarios[century];
}
